apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: frozen-fly-go 
  janus-idp.io/tekton: frozen-fly-go
  backstage.io/kubernetes-id: frozen-fly-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: frozen-fly-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  